title: Networking Lessons
category: teach
lessons:
  1: How do computers communicate?
  2: "The Internet of Things: How do computers control other computers?"
  3: Dynamic Host Configuration Protocol (DHCP)
  4: Domain Name System (DNS)
